/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */


/**
 * @class
 * Initializes a new instance of the Employee class.
 * @constructor
 * Represents the employee.
 * @member {number} [id] Gets or sets the employee identifier.
 * 
 * @member {string} [name] Gets or sets the employee name.
 * 
 */
export interface Employee {
    id?: number;
    name?: string;
}
